<?php
namespace common\widgets\qr;

use yii\base\Widget;

class Qr extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}